### ISSUE TITLE
Cannot select any valid SQL engine.

### ISSUE THREAD

**Issue by TemKaSD** [retailcrm/prestashop-module#186]
Здравствуйте. При выполнении команды php modules/retailcrm/cli.php --query-web-jobs престашоп выдает исключение: *ERROR* 	v1.7.8.6	2022/07/22 - 19:59:26: Cannot select any valid SQL engine. at line 302 in file classes/db/Db.php

**Comment by gleemand** [comment]
Добрый день.
Не удалось воспроизвести проблему.

Исключение выбрасывается на строке 302 в файле classes/db/Db.php
`/**
     * Returns the best child layer database class.
     *
     * @return string
     */
    public static function getClass()
    {
        $class = '';
        if (PHP_VERSION_ID >= 50200 && extension_loaded('pdo_mysql')) {
            $class = 'DbPDO';
        } elseif (extension_loaded('mysqli')) {
            $class = 'DbMySQLi';
        }

        if (empty($class)) {
            throw new PrestaShopException('Cannot select any valid SQL engine.');
        }

        return $class;
    }`
Похоже, что Prestashop не может найти php расширение, необходимое для подключения к БД.

**Comment by TemKaSD** [comment]
Странно, всё заработало само собой.
