### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by TemKaSD** [retailcrm/prestashop-module#187]
Здравствуйте. После обновления модуля допоследней версии, перестали выгружаться заказы. Вот из логов: nvalid argument supplied for foreach() in /modules/retailcrm/lib/RetailcrmExport.php on line 466.

![image](https://user-images.githubusercontent.com/6318282/181307377-6b2e127f-50d0-4f58-926f-cbe9102a871b.png)

![image](https://user-images.githubusercontent.com/6318282/181307456-b9e0808e-f991-4edd-9592-758dd58ae444.png)

**Comment by gleemand** [comment]
Здравствуйте. Не удалось воспроизвести проблему.

Класс `RetailcrmExport` используется для ручной выгрузки заказов. Какие данные вводили в поле `ID заказов` для выгрузки?

Также, поделитесь, пожалуйста, текстом ошибок, появляющимся при наведении на статус `Ошибка`.

После этого обновите модуль до еще более последней версии и попробуйте выгрузить ошибочные заказы.

**Comment by TemKaSD** [comment]
1. Обновил модуль до версии 3.4.9.
2. Почистил кеш в престашоп.
3. Удалил файлы логов в каталоге /var/logs/
4. Зашел в админке Simla.com > Работа с заказами > Выгрузить повторно.

После нажатия на кнопу пишет, что заказ выгружен

![image](https://user-images.githubusercontent.com/6318282/181478215-17922980-67e5-4f3c-b643-0b3e225e2d89.png)

В РетеилСРМ он НЕ появился, после обновления страницы в админке пишет Статус "Ошибка".

![image](https://user-images.githubusercontent.com/6318282/181478477-aff1f9ee-9de7-4ace-87cb-10ff952781a1.png)

**Comment by TemKaSD** [comment]
@gleemand Заменил app.js с этого изменения: https://github.com/retailcrm/prestashop-module/pull/188 всё еще не работает.

**Comment by gleemand** [comment]
Попробуйте обновить модуль, очистить кэш и снова выгрузить заказы.
Если проблема сохранится, то пришлите, пожалуйста, тело запроса к `index.php?controller=RetailcrmOrders`, который отправляется при нажатии кнопки "Выгрузить повторно"
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/21148657/181526619-b01dafa0-5697-448f-97c3-7ca0bebc08a5.png">

**Comment by TemKaSD** [comment]
@gleemand 
![image](https://user-images.githubusercontent.com/6318282/181574492-d72af3b9-1574-438d-8d8b-eaf704c3bc79.png)

**Comment by gleemand** [comment]
Видно, что используется старый app.js из кэша, т. к. запрос в последней версии имеет параметр `orders`.
Могу посоветовать очистить все возможные кэши (браузера, prestashop, сервера и т.д.).

**Comment by TemKaSD** [comment]
Спасибо, почистил кеш браузера, всё заработало.

Наверное, есть смысл добавить версии для JS файлов ))
