### ISSUE TITLE
Вопрос по настройке модуля

### ISSUE THREAD

**Issue by TemKaSD** [retailcrm/prestashop-module#189]
Здравствуйте. Скажите пожалуйста, как сделать так, чтобы заказы из RetailCRM никогда не выгружались на сайт, если заказы созданы не через сайт, соответственно синхронизация статусов нужна, но только с заказами, оформленными через сайт.

**Comment by gleemand** [comment]
Можете воспользоваться возможностью [https://github.com/retailcrm/prestashop-module/blob/master/doc/3.%20Customization/Filters.md](кастомизации с помощью фильтров).

Используйте фильтры RetailcrmFilterOrdersHistory...

Если появятся вопросы, пишите в техническую поддержку на странице настроек модуля или на официальном сайте RetailCRM.

**Comment by TemKaSD** [comment]
@gleemand Здравствуйте. Извините за беспокойство. Вопрос всё еще актуален, пробовал обращаться в поддержку из личного кабинета, они сказали, что никто кроме нас не просил реализовать такой функционал, точнее фильтрацию и наверно перед вами не поставили задачу.

Нам очень нужен этот фильтр, мы работаем на разных площадках, например, при синхронизации заказов, у нас создалось уже порядка 10 000 клиентов из Ozon, которых, в базе престашоп не должно быть.

Вообще это не логично, когда что-то НЕ престашоповское выгружается в престашоп, ведь CRM для этого и нужна, чтобы работать в одном личном кабинете, и не создавать этот мусор в базе престашоп.

Очень просим реализовать фильтр.

**Comment by dima-uryvskiy** [comment]
Добрый день, а у вас для OZON и PrestaShop один и тот же ключ ?
Напишите еще раз в поддержку, необходимо произвести более подробный анализ вашей проблемы.
