### ISSUE TITLE
Может как то убрать хардкорное указание статуса? зачастую такого статуса нет

### ISSUE THREAD

**Issue by dmamontov** [retailcrm/prestashop-module#24]
https://github.com/retailcrm/prestashop-module/blob/8b1c9ec5deb650313edd4484aedbc2c6ca0404cb/retailcrm/job/export.php#L62

**Comment by gwinn** [comment]
https://github.com/retailcrm/prestashop-module/pull/25/commits/d8300047cebc31c4da36588695115d053570353b
