### ISSUE TITLE
ошибка 500 при синхронизации через cron sync

### ISSUE THREAD

**Issue by evropol** [retailcrm/prestashop-module#31]
Не получается синхронизировать статусы заказов из crm в магазин.
установил команду в крон но команда не выполняется изза 500 ошибки.
вот  что написано при включение дебага:

Fatal error: Uncaught exception 'PrestaShopException' with message 'Property Customer->passwd is empty' in /home/a/domains/evropol/public_html/classes/ObjectModel.php:917 Stack trace: #0 /home/a/domains/evropol/public_html/classes/ObjectModel.php(246): ObjectModelCore->validateFields() #1 /home/a/domains/evropol/public_html/classes/ObjectModel.php(652): ObjectModelCore->getFields() #2 /home/a/domains/evropol/public_html/classes/Customer.php(253): ObjectModelCore->update(true) #3 /home/a/domains/evropol/public_html/modules/retailcrm/lib/RetailcrmHistory.php(53): CustomerCore->update() #4 /home/a/domains/evropol/public_html/modules/retailcrm/job/sync.php(30): RetailcrmHistory::customersHistory() #5 {main} thrown in /home/a/domains/evropol/public_html/classes/ObjectModel.php on line 917

**Comment by iyzoer** [comment]
Видимо модуль пытается сохранить данные клиента, у которого есть внешний код, но его нет на сайте. Возможно у Вас какие-то другие интеграции есть на этом ключе? Или клиенты из других внешних источников?

**Comment by iyzoer** [comment]
Добавили обработку ошибки в новой версии модуля.
