### ISSUE TITLE
PS 1.6.1.4 ошибка 500 sync.php

### ISSUE THREAD

**Issue by TemKaSD** [retailcrm/prestashop-module#53]
Здравствуйте. Имеем проблему с синхронизацией заказов, престашоп 1.6.1.4 версия модуля последняя.

Ошибка в логе: count(): Parameter must be an array or an object that implements Countable in /classes/ObjectModel.php on line 644

![Screenshot_1](https://user-images.githubusercontent.com/6318282/67760410-fbe58800-fa8c-11e9-9c6c-8ce9564bd573.png)
![Screenshot_2](https://user-images.githubusercontent.com/6318282/67760422-0869e080-fa8d-11e9-9f79-3fb0e7e2df17.png)

**Comment by TemKaSD** [comment]
Вы уверены что здесь нужно указать индекс 1 ? https://github.com/retailcrm/prestashop-module/blob/master/retailcrm/lib/RetailcrmHistory.php#L698

У меня только 0 индекс существует, или вы не знаете, что в php индексы с нуля идут?
![Screenshot_1](https://user-images.githubusercontent.com/6318282/67764874-97c7c180-fa96-11e9-8fc8-2df99d941609.png)

**Comment by Neur0toxine** [comment]
Здравствуйте. Не удаётся повторить проблему. Пожалуйста, опишите подробнее ситуацию, в которой у вас произошла данная ошибка. Например, может помочь информация о том, что используется / не используется возможность добавления одинаковых товаров как разных товарных позиций.

**Comment by Neur0toxine** [comment]
Добрый день. Сегодня удалось повторить проблему. Ошибка будет исправлена в следующей версии модуля.
