### ISSUE TITLE
Обнаружен вирус

### ISSUE THREAD

**Issue by TemKaSD** [retailcrm/prestashop-module#57]
Здравствуйте. При скачивании из релизов:

![Screenshot_1](https://user-images.githubusercontent.com/6318282/75581481-4fa4c400-5ab5-11ea-8ecc-b4de2b797869.png)
![Screenshot_2](https://user-images.githubusercontent.com/6318282/75581570-7d8a0880-5ab5-11ea-8882-4a725164c01e.png)

**Comment by Neur0toxine** [comment]
Добрый день! Действительно, видим ложноположительное срабатывание Защитника Windows. Скорее всего, оно связано с тем, что для работы модуля необходимы внешние соединения к нашему API (к примеру, для выгрузки заказов и клиентов), также модуль позволяет подключить к сайту Daemon Collector, для этого к front-office подключается JavaScript-код, который реализует функциональность Daemon Collector. Такие техники нередко используют вредоносные скрипты на PHP - отсюда и ложное срабатывание.

Вирусов в модуле нет. Код модуля в релизах идентичен коду на GitHub. При любом сомнении вы всегда можете проверить код самостоятельно. Также [здесь можно посмотреть результат проверки на Virustotal](https://www.virustotal.com/gui/file/c41f7e4cdaae965c165ea29e039029db64a5c6981ce2806c96acc3370a88fe37/detection).

Заявка на ложное срабатывание уже отправлена. Microsoft рассматривает такие заявки в течение месяца, по прошествии этого времени проблема должна исчезнуть.

Спасибо за наблюдательность!

**Comment by gwinn** [comment]
Добрый день! Действительно, видим ложноположительное срабатывание Защитника Windows. Скорее всего, оно связано с тем, что для работы модуля необходимы внешние соединения к  API retailCRM (к примеру, для выгрузки заказов и клиентов), также модуль позволяет подключить к сайту Daemon Collector, для этого к front-office подключается JavaScript-код, который реализует функциональность Daemon Collector. Такие техники нередко используют вредоносные скрипты на PHP - отсюда и ложное срабатывание.

Вирусов в модуле нет. Код модуля в релизах идентичен коду на GitHub. При любом сомнении вы всегда можете проверить код самостоятельно. Также [здесь можно посмотреть результат проверки на Virustotal](https://www.virustotal.com/gui/file/c41f7e4cdaae965c165ea29e039029db64a5c6981ce2806c96acc3370a88fe37/detection).

Заявка на ложное срабатывание уже отправлена. Microsoft рассматривает такие заявки в течение месяца, по прошествии этого времени проблема должна исчезнуть.

Спасибо за наблюдательность.

**Comment by Neur0toxine** [comment]
Добрый день. Microsoft обработала заявку на удаление модуля из списка сигнатур Windows Defender. Для обновления сигнатур можно произвести следующие действия:

1. Откройте командную строку от имени администратора, перейдите в директорию `c:\Program Files\Windows Defender`
2. Выполните команду `MpCmdRun.exe -removedefinitions -dynamicsignatures`
3. Выполните команду `MpCmdRun.exe -SignatureUpdate`

После вышеописанных действий ложное срабатывание должно исчезнуть. Выполнять эти действия необязательно - со временем сигнатуры антивируса обновятся самостоятельно, и ложное срабатывание пропадёт.
