### ISSUE TITLE
Method \"getRawResponse\" not found

### ISSUE THREAD

**Issue by TemKaSD** [retailcrm/prestashop-module#71]
Здравствуйте. Решил обновить модуль до последней версии, при сохранении настроек ошибка:

Uncaught PHP Exception InvalidArgumentException: "Method "getRawResponse" not found" at /modules/retailcrm/lib/RetailcrmApiResponse.php line 83 {"exception":"[object] (InvalidArgumentException(code: 0): Method \"getRawResponse\" not found at /modules/retailcrm/lib/RetailcrmApiResponse.php:83)"} []

**Comment by TemKaSD** [comment]
Удалил старый модуль, поставил чистый новый, работает.

**Comment by Neur0toxine** [comment]
Добрый день!

Подобного вида проблемы зачастую исправляются очисткой кэша. К сожалению, автоматизировать это нельзя.
В кодовой базе модуля указанной проблемы нет.
